pip install flask 
pip install flask_session 
pip install re
pip install bcrypt 
pip install jwt
pip install werkzeug.security 
pip install werkzeug.utils 
pip install pyfiglet
pip install secrets
pip install csv
pip install flask_login 
pip install wtforms.validators 
pip install psycopg2
pip install psycopg2 
pip install os
pip install urllib.request
pip install flask_mysqldb 
pip install flask_login 
pip install wtforms.validators 